name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      root_page_url:
        description: 'Root Page URL(public)'
        required: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Input $root_page_url :  ${{ github.event.inputs.root_page_url }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: hwangseonbi/notion2geekdoc

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: python notion2geekdoc ${{ github.event.inputs.root_page_url }}
        env:
          NOTION_TOKEN_V2: ${{ secrets.NOTION_TOKEN_V2 }}
